-- Baseline schema for CampusBook.
--
-- This captures the schema Hibernate generated up to this point (institutions,
-- users, halls, bookings, notifications). From here on the schema is owned by
-- Flyway, not ddl-auto: every change ships as a new V<n>__ migration and
-- Hibernate runs in `validate` mode against what these scripts produce.
--
-- Constraint names are readable rewrites of Hibernate's generated ones; the
-- column names and types match the entities exactly so `validate` passes.

CREATE TABLE institutions (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                         VARCHAR(255) NOT NULL,
    tier                         VARCHAR(255) NOT NULL,
    analytics_enabled            BOOLEAN NOT NULL,
    custom_notifications_enabled BOOLEAN NOT NULL,
    api_integrations_enabled     BOOLEAN NOT NULL,
    created_at                   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uk_institutions_name UNIQUE (name),
    CONSTRAINT institutions_tier_check
        CHECK (tier IN ('FREE', 'CAMPUS_PRO', 'ENTERPRISE'))
);

CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name            VARCHAR(255) NOT NULL,
    email                VARCHAR(255) NOT NULL,
    staff_or_student_id  VARCHAR(255) NOT NULL,
    password             VARCHAR(255) NOT NULL,
    role                 VARCHAR(255),
    department           VARCHAR(255),
    institution_id       BIGINT NOT NULL,
    created_at           TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_staff_or_student_id UNIQUE (staff_or_student_id),
    CONSTRAINT users_role_check
        CHECK (role IN ('ADMIN', 'LECTURER', 'STUDENT_LEADER')),
    CONSTRAINT fk_users_institution
        FOREIGN KEY (institution_id) REFERENCES institutions (id)
);

CREATE TABLE halls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block           VARCHAR(255) NOT NULL,
    room_code       VARCHAR(255) NOT NULL,
    capacity        INTEGER,
    hasac           BOOLEAN NOT NULL,
    has_microphone  BOOLEAN NOT NULL,
    has_projector   BOOLEAN NOT NULL,
    active          BOOLEAN NOT NULL,
    institution_id  BIGINT NOT NULL,
    CONSTRAINT uk_halls_room_code UNIQUE (room_code),
    CONSTRAINT fk_halls_institution
        FOREIGN KEY (institution_id) REFERENCES institutions (id)
);

CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose           VARCHAR(255) NOT NULL,
    notes             VARCHAR(1000),
    attendance        INTEGER,
    start_time        TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_time          TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status            VARCHAR(255),
    rejection_reason  VARCHAR(255),
    user_id           BIGINT NOT NULL,
    hall_id           BIGINT NOT NULL,
    approved_by       BIGINT,
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT bookings_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_hall
        FOREIGN KEY (hall_id) REFERENCES halls (id),
    CONSTRAINT fk_bookings_approved_by
        FOREIGN KEY (approved_by) REFERENCES users (id)
);

CREATE TABLE notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(255) NOT NULL,
    title               VARCHAR(255) NOT NULL,
    message             VARCHAR(255) NOT NULL,
    related_booking_id  BIGINT,
    is_read             BOOLEAN NOT NULL,
    user_id             BIGINT NOT NULL,
    created_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT notifications_type_check
        CHECK (type IN ('NEW_BOOKING_REQUEST', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'BOOKING_CANCELLED')),
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
