-- One-time password-reset codes (OTP). Only a hash of the code is stored, never
-- the code itself, so a leaked database row can't be used to reset an account.
-- Codes expire, are single-use (consumed_at), and hard-fail after too many wrong
-- attempts.

CREATE TABLE password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    token_hash   VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    consumed_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    attempts     INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);
