-- Append-only audit trail for booking state changes: who did what, when, and why.
-- Answers "who approved this room and when" without inferring it from the
-- booking's current row, which only ever shows the latest state.

CREATE TABLE booking_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT NOT NULL,
    actor_id    BIGINT,
    action      VARCHAR(255) NOT NULL,
    details     VARCHAR(500),
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT booking_audit_action_check
        CHECK (action IN ('CREATED', 'APPROVED', 'REJECTED', 'CANCELLED', 'RESCHEDULED')),
    CONSTRAINT fk_booking_audit_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    -- Actor is nullable and never cascades: deleting a user must not erase the
    -- record that an action happened.
    CONSTRAINT fk_booking_audit_actor
        FOREIGN KEY (actor_id) REFERENCES users (id)
);

CREATE INDEX idx_booking_audit_booking ON booking_audit (booking_id, created_at);
