-- One-time email-verification codes (OTP), same shape as password_reset_tokens.
-- Only a hash of the code is stored, never the code itself.

CREATE TABLE email_verification_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    token_hash   VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    consumed_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    attempts     INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_email_verification_tokens_user ON email_verification_tokens (user_id);

ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Every row that already exists was created before this feature did — via the
-- seeder, an admin, a platform admin, or a pre-feature self-registration. None
-- of them proved anything by finishing a challenge that didn't exist yet, so
-- gating them retroactively would just lock out every current account with no
-- way back in. Only rows a self-registration inserts AFTER this migration are
-- meant to start FALSE — that's UserService.registerUser's job, not this
-- backfill's.
UPDATE users SET email_verified = TRUE WHERE email_verified = FALSE;
